default: -p chrome -p html --no-source --color --format pretty 
cucumber: -r features
dot: --format progress
html: --format html --out reports/execution_report.html
chrome: BROWSER=chrome
chrome_headless: BROWSER=chrome_headless
firefox: BROWSER=firefox
firefox_headless: BROWSER=firefox_headless